# Generated by Django 5.0.1 on 2024-02-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="posts_count",
            field=models.IntegerField(default=0),
        ),
    ]
