# Generated by Django 5.0.1 on 2024-02-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0005_user_posts_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
