# Generated by Django 5.0.1 on 2024-02-28 15:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0006_user_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="people_you_may_know",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
