# Generated by Django 5.0.1 on 2024-02-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0004_post_comment_count_alter_postattachments_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trends",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hashtag", models.CharField(max_length=255)),
                ("occurances", models.IntegerField()),
            ],
        ),
    ]
