# Generated by Django 5.0.1 on 2024-02-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversationmessage",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
